@extends('layouts.site')
@section('title', $article->title . ' — ' . site('brand.name'))
@section('content')
@php($au = $article->author ?? [])
@php($toc = array_values(array_filter($article->content ?? [], fn ($b) => ($b['type'] ?? '') === 'h2')))
<div data-testid="article-detail-page" x-data>
  <div class="mx-auto max-w-7xl px-4 md:px-6 lg:px-10 pt-8">
    <div class="flex flex-wrap gap-2">@foreach($article->tags ?: [$article->category, $article->read_time] as $i => $t)<x-pill :tone="$i === 0 ? 'brand' : ($i === 3 ? 'sage' : 'sand')" :uppercase="true">{{ $t }}</x-pill>@endforeach</div>
    <h1 class="font-display font-bold text-ink text-3xl md:text-5xl leading-[1.1] tracking-tight mt-5 max-w-4xl">{{ $article->title }}</h1>
    <p class="text-sand text-base md:text-lg mt-4 max-w-3xl leading-relaxed">{{ $article->subtitle ?: $article->excerpt }}</p>
    <div class="flex flex-wrap items-center justify-between gap-4 mt-6 pb-6 border-b border-ink/8">
      <div class="flex items-center gap-3"><img src="{{ $au['avatar'] ?? '' }}" alt="" class="w-11 h-11 rounded-full object-cover bg-cream-200"><div><div class="font-semibold text-ink text-sm flex items-center gap-1">{{ $au['name'] ?? '' }} {!! icon('BadgeCheck', 'w-4 h-4 text-sage-700') !!}</div><div class="text-xs text-sand">{{ $au['role'] ?? '' }} • {{ fmt_date($article->date) }} • Fact-checked by Bali Tourism Board</div></div></div>
      <div class="flex items-center gap-2 text-xs text-sand"><span class="uppercase tracking-wider font-bold mr-1">Share</span>@foreach(['Share2', 'Link2', 'Bookmark'] as $ic)<button type="button" @click="navigator.clipboard?.writeText(location.href); toast('Link copied to clipboard')" class="w-9 h-9 rounded-full bg-cream-100 hover:bg-brand-50 hover:text-brand flex items-center justify-center transition-colors">{!! icon($ic) !!}</button>@endforeach</div>
    </div>
    <div class="mt-8"><div class="relative rounded-3xl overflow-hidden h-72 md:h-[480px] shadow-card"><img src="{{ $article->image }}" alt="{{ $article->title }}" class="w-full h-full object-cover"><div class="absolute top-4 right-4"><x-pill tone="dark">{!! icon('Camera', 'w-3 h-3') !!} {{ $au['name'] ?? '' }}</x-pill></div></div>@if($article->image_caption)<p class="text-xs text-sand italic mt-3">{{ $article->image_caption }}</p>@endif</div>
  </div>

  <div class="mx-auto max-w-7xl px-4 md:px-6 lg:px-10 py-12 grid lg:grid-cols-3 gap-10 items-start">
    <article class="lg:col-span-2">
      @if($article->highlights)<div class="bg-cream-100 rounded-3xl p-6 md:p-8 border border-brand-100"><h3 class="font-display font-bold text-brand text-xl flex items-center gap-2">{!! icon('ShieldCheck', 'w-5 h-5') !!} Curator's Highlights</h3><p class="text-sm text-ink/70 mt-2">Before lacing up your shoes, keep these essential rules in mind:</p><div class="grid sm:grid-cols-2 gap-4 mt-5">@foreach($article->highlights as $i => $h)<div class="flex gap-3 text-sm text-ink font-medium">{!! icon(['Clock', 'Car', 'Landmark', 'UtensilsCrossed'][$i % 4], 'w-4 h-4 text-brand shrink-0 mt-0.5') !!} {{ $h }}</div>@endforeach</div></div>@endif
      @foreach($article->content ?? [] as $b)
        @switch($b['type'] ?? '')
          @case('h2')<h2 class="font-display font-bold text-ink text-2xl md:text-3xl mt-12 mb-4 leading-tight">{{ $b['text'] ?? '' }}</h2>@break
          @case('p')<div class="rich-content text-ink/80 leading-[1.85] text-[16px] mt-4">{!! rich_html($b['text'] ?? '') !!}</div>@break
          @case('quote')<blockquote class="my-8 border-l-4 border-brand bg-brand-50/60 rounded-r-2xl px-6 py-5"><p class="font-serif italic text-ink text-lg leading-relaxed">"{{ $b['text'] ?? '' }}"</p>@if(!empty($b['cite']))<div class="text-[10px] uppercase tracking-[0.16em] font-bold text-brand-700 mt-3">— {{ $b['cite'] }}</div>@endif</blockquote>@break
          @case('list')<ul class="mt-4 space-y-2">@foreach($b['items'] ?? [] as $i)<li class="flex items-start gap-2.5 text-ink/80"><span class="w-1.5 h-1.5 rounded-full bg-brand mt-2.5 shrink-0"></span> {{ $i }}</li>@endforeach</ul>@break
          @case('steps')<div class="relative mt-8 pl-8 border-l-2 border-dashed border-sage-700/30 space-y-5">@foreach($b['items'] ?? [] as $i => $s)<div class="relative bg-white rounded-2xl p-5 shadow-soft"><span class="absolute -left-[45px] top-4 w-7 h-7 rounded-full text-white text-xs font-bold flex items-center justify-center {{ $i % 2 === 0 ? 'bg-brand-800' : 'bg-forest' }}">{{ $i + 1 }}</span><div class="flex flex-wrap items-center justify-between gap-2"><span class="text-[10px] uppercase tracking-[0.16em] font-bold text-brand-700">{{ $s['time'] ?? '' }}</span>@if(!empty($s['tag']))<x-pill :tone="$i % 2 === 0 ? 'brand-soft' : 'sage'">{{ $s['tag'] }}</x-pill>@endif</div><div class="font-display font-bold text-ink text-lg mt-1">{{ $s['title'] ?? '' }}</div><p class="text-sm text-ink/70 leading-relaxed mt-1.5">{{ $s['desc'] ?? '' }}</p></div>@endforeach</div>@break
          @case('gallery')<div class="mt-8"><div class="font-display font-bold text-ink text-lg mb-3">Moments from the Expedition</div><div class="grid grid-cols-3 gap-3">@foreach($b['items'] ?? [] as $i => $g)<div class="relative rounded-2xl overflow-hidden h-52 img-zoom {{ $i === 0 ? 'col-span-2' : '' }}"><img src="{{ $g['src'] ?? '' }}" alt="{{ $g['label'] ?? '' }}" class="w-full h-full object-cover"><div class="absolute inset-0 bg-gradient-to-t from-ink/70 to-transparent"></div><div class="absolute bottom-3 left-3 text-white text-xs">{{ $g['label'] ?? '' }}</div></div>@endforeach</div></div>@break
          @case('cards')<div class="grid sm:grid-cols-2 gap-4 mt-6">@foreach($b['items'] ?? [] as $c)<div class="bg-white rounded-2xl p-5 shadow-soft"><span class="w-10 h-10 rounded-xl bg-brand-50 text-brand flex items-center justify-center">{!! icon($c['icon'] ?? 'Info', 'w-5 h-5') !!}</span><div class="font-display font-bold text-ink mt-4">{{ $c['title'] ?? '' }}</div><p class="text-xs text-sand leading-relaxed mt-2">{{ $c['desc'] ?? '' }}</p></div>@endforeach</div>@break
        @endswitch
      @endforeach
      <div class="mt-12 bg-cream-100 rounded-3xl p-6 md:p-8 border border-ink/5"><div class="flex flex-col sm:flex-row gap-5"><img src="{{ $au['avatar'] ?? '' }}" alt="" class="w-16 h-16 rounded-full object-cover shrink-0 bg-cream-200"><div class="flex-1"><div class="flex flex-wrap items-center justify-between gap-2"><div><div class="font-display font-bold text-ink text-lg">Written by {{ $au['name'] ?? '' }}</div><div class="text-xs font-semibold text-brand">{{ $au['role'] ?? '' }}</div></div>@if(!empty($au['license']))<x-pill tone="sand">{{ $au['license'] }}</x-pill>@endif</div><div class="rich-content text-sm text-ink/70 leading-relaxed mt-3">{!! rich_html($au['bio'] ?? '') !!}</div><a href="{{ wa_url("Halo, saya punya pertanyaan tentang artikel \"{$article->title}\".") }}" target="_blank" rel="noopener" class="mt-4 text-sm font-semibold text-sage-700 inline-flex items-center gap-2 hover:text-brand transition-colors">{!! icon('MessageCircle') !!} Have questions about this route? Ask directly via WhatsApp Concierge</a></div></div></div>
      <div class="mt-8 py-6 border-y border-ink/8 flex flex-wrap items-center justify-between gap-3"><span class="text-sm text-ink">Was this travel guide helpful?</span><div class="flex gap-2"><button type="button" @click="toast('Thanks for your feedback!')" class="btn-outline !py-2 !px-4 !text-xs">{!! icon('ThumbsUp', 'w-3.5 h-3.5') !!} Yes, very helpful</button><button type="button" @click="toast('We appreciate your honesty. Our editors will review this guide.')" class="btn-outline !py-2 !px-4 !text-xs">{!! icon('ThumbsDown', 'w-3.5 h-3.5') !!} Could be better</button></div></div>
    </article>
    <div class="space-y-5 lg:sticky lg:top-24">
      @if($toc)<div class="bg-cream-100 rounded-3xl p-6 border border-ink/5"><div class="font-display font-bold text-ink flex items-center gap-2">{!! icon('BookOpen', 'w-4 h-4 text-brand') !!} Table of Contents</div><ul class="mt-4 space-y-2 text-sm">@foreach($toc as $i => $t)<li class="flex items-start gap-2 {{ $i === 0 ? 'text-brand font-semibold' : 'text-ink/70' }}"><span class="w-1.5 h-1.5 rounded-full mt-2 shrink-0 {{ $i === 0 ? 'bg-brand' : 'bg-ink/30' }}"></span> {{ $t['text'] ?? '' }}</li>@endforeach</ul></div>@endif
      @if($article->facts)<div class="bg-white rounded-3xl p-6 shadow-soft"><div class="font-display font-bold text-ink flex items-center gap-2">{!! icon('Info', 'w-4 h-4 text-brand') !!} Traveler Fast Facts</div><div class="mt-4 divide-y divide-ink/8">@foreach($article->facts as $f)<div class="flex items-center justify-between py-2.5 text-sm"><span class="text-sand">{{ $f['label'] ?? '' }}</span><span class="font-semibold text-ink text-right">{{ $f['value'] ?? '' }}</span></div>@endforeach</div></div>@endif
      <div class="bg-white rounded-3xl p-6 shadow-soft"><div class="font-display font-bold text-ink flex items-center gap-2">{!! icon('Landmark', 'w-4 h-4 text-brand') !!} Related Guides &amp; Stories</div><div class="mt-4 space-y-4">@foreach($related as $r)<a href="{{ route('articles.show', $r->slug) }}" class="flex gap-3 group"><img src="{{ $r->image }}" alt="" class="w-16 h-14 rounded-xl object-cover shrink-0"><div><div class="text-sm font-semibold text-ink leading-snug group-hover:text-brand transition-colors clamp-2">{{ $r->title }}</div><div class="text-xs text-sand mt-1 flex items-center gap-1">{!! icon('Clock', 'w-3 h-3') !!} {{ $r->read_time }}</div></div></a>@endforeach</div></div>
    </div>
  </div>
  <x-newsletter eyebrow="Private Travel Journal" title="Make Moments That Last Across Bali" desc="Receive exclusive seasonal itineraries, early access to private yacht departures, and verified Balinese cultural calendars directly to your inbox." cta="Join Privileges" />
</div>
@endsection
